version: "3.8"

services:
  auth_microservice:
    container_name: auth_microservice
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
      - "5555:5555"
      - "7070:7070"
    environment:
      - PORT=5000
    depends_on:
      - postgresql
      - redis
      # - prometheus
      # - node_exporter
      # - grafana
    restart: always
    volumes:
      - ./:/app
    networks:
      - auth_network

  redis:
    image: redis:7.0-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - auth_network

  postgresql:
    image: postgres:13-alpine
    container_name: auth_postgresql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge
